### ISSUE TITLE
How to use in offline environment?

### ISSUE THREAD

**Issue by prokie** [chrisjsewell/sphinx-tippy#3]
Hello!

How can I use this package in an offline environment? I tried downloading tippy.js from https://unpkg.com/tippy.js@0.11.3/dist/tippy.js and put it in `_static/js/tippy.js` and then my `conf.py` looks like this

```
extensions = ["sphinx_tippy"]

templates_path = ["_templates"]
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = "sphinx_rtd_theme"
html_static_path = ["_static"]

pygments_style = "sphinx"
html_css_files = [
    "css/custom.css",
]
html_js_files = ["js/plotly.js", "js/tippy.js"]
tippy_js = ("js/tippy.js",)
```
But I get `Uncaught ReferenceError: tippy is not defined`  in firefox console

**Comment by chrisjsewell** [comment]
Heya, I'm not sure off hand I'm afraid, but you may  want to have a look in your browser's developers tools, to have a look at the order things are being loaded.
For instance in firefox:

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/2997570/219820621-241618f1-a64c-4281-82c4-467bbb4e3ada.png">

**Comment by chrisjsewell** [comment]
i.e. tippy needs to have been loaded, before `_static/tippy/index...js`

**Comment by prokie** [comment]
Yes, and it is. I am using the the tippy.js with popper.js included but I am still getting this warning in the console.

```
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: file:///proj/build/html/_static/js/tippy.js
Source Map URL: popper.js.map
```

**Comment by prokie** [comment]
Does it work for you with?

html_js_files = ["js/tippy.js"]
tippy_js = ("js/tippy.js",)

**Comment by prokie** [comment]
I got it working now, will update the issue tomorrow with the solution. One problem, that made debugging a lot tougher was this issue with sphinx https://github.com/sphinx-doc/sphinx/issues/11163. With an empty `searchindex.js`,  no hovers are possible.

**Comment by prokie** [comment]
To get offline mode working I need to have the following in conf.py
```
html_js_files = ["js/tippy.js", "js/popper.js"]
tippy_js = ["js/popper.js", "js/tippy.js"]
```
Where tippy is downloaded from https://unpkg.com/tippy.js@6.3.7/dist/tippy-bundle.umd.min.js and popper is downloaded from https://unpkg.com/@popperjs/core@2.11.6/dist/umd/popper.min.js

**Comment by pique-b** [comment]
By following the steps above and updating the ``conf.py`` got it to work in offline mode. Tested it by clearing the *build* files and re-compiling.

The *.js* files were downloaded from sources as suggested [here](https://unpkg.com/tippy.js@6.3.7/dist/tippy-bundle.umd.min.js) and [here](https://unpkg.com/@popperjs/core@2.11.6/dist/umd/popper.min.js)) .

However, tooltips for links such as *wikipedia* and *DOI* fails to load, even in *online mode*. Compiling the docs again while connected to the net **also does not make them to work**. Only when all generated files are removed with ``make clean`` and compiling again (while connected to the net) enables them again.
